use crate::cpu::instructions::{instruction_set::*, Addrmode::*, Instr};

// code generated by python
pub fn lookup(opcode: u8) -> Instr {
    match opcode {
        0x00 => Instr {
            run: brk,
            mode: Impl,
            cycles: 7,
        },
        0x01 => Instr {
            run: ora,
            mode: XInd,
            cycles: 6,
        },
        0x05 => Instr {
            run: ora,
            mode: Zpg,
            cycles: 3,
        },
        0x06 => Instr {
            run: asl,
            mode: Zpg,
            cycles: 5,
        },
        0x08 => Instr {
            run: php,
            mode: Impl,
            cycles: 3,
        },
        0x09 => Instr {
            run: ora,
            mode: Imm,
            cycles: 2,
        },
        0x0A => Instr {
            run: asl,
            mode: A,
            cycles: 2,
        },
        0x0D => Instr {
            run: ora,
            mode: Abs,
            cycles: 4,
        },
        0x0E => Instr {
            run: asl,
            mode: Abs,
            cycles: 6,
        },
        0x10 => Instr {
            run: bpl,
            mode: Rel,
            cycles: 2,
        },
        0x11 => Instr {
            run: ora,
            mode: IndY,
            cycles: 5,
        },
        0x15 => Instr {
            run: ora,
            mode: ZpgX,
            cycles: 4,
        },
        0x16 => Instr {
            run: asl,
            mode: ZpgX,
            cycles: 6,
        },
        0x18 => Instr {
            run: clc,
            mode: Impl,
            cycles: 2,
        },
        0x19 => Instr {
            run: ora,
            mode: AbsY,
            cycles: 4,
        },
        0x1D => Instr {
            run: ora,
            mode: AbsX,
            cycles: 4,
        },
        0x1E => Instr {
            run: asl,
            mode: AbsX,
            cycles: 7,
        },
        0x20 => Instr {
            run: jsr,
            mode: Abs,
            cycles: 6,
        },
        0x21 => Instr {
            run: and,
            mode: XInd,
            cycles: 6,
        },
        0x24 => Instr {
            run: bit,
            mode: Zpg,
            cycles: 3,
        },
        0x25 => Instr {
            run: and,
            mode: Zpg,
            cycles: 3,
        },
        0x26 => Instr {
            run: rol,
            mode: Zpg,
            cycles: 5,
        },
        0x28 => Instr {
            run: plp,
            mode: Impl,
            cycles: 4,
        },
        0x29 => Instr {
            run: and,
            mode: Imm,
            cycles: 2,
        },
        0x2A => Instr {
            run: rol,
            mode: A,
            cycles: 2,
        },
        0x2C => Instr {
            run: bit,
            mode: Abs,
            cycles: 4,
        },
        0x2D => Instr {
            run: and,
            mode: Abs,
            cycles: 4,
        },
        0x2E => Instr {
            run: rol,
            mode: Abs,
            cycles: 6,
        },
        0x30 => Instr {
            run: bmi,
            mode: Rel,
            cycles: 2,
        },
        0x31 => Instr {
            run: and,
            mode: IndY,
            cycles: 5,
        },
        0x35 => Instr {
            run: and,
            mode: ZpgX,
            cycles: 4,
        },
        0x36 => Instr {
            run: rol,
            mode: ZpgX,
            cycles: 6,
        },
        0x38 => Instr {
            run: sec,
            mode: Impl,
            cycles: 2,
        },
        0x39 => Instr {
            run: and,
            mode: AbsY,
            cycles: 4,
        },
        0x3D => Instr {
            run: and,
            mode: AbsX,
            cycles: 4,
        },
        0x3E => Instr {
            run: rol,
            mode: AbsX,
            cycles: 7,
        },
        0x40 => Instr {
            run: rti,
            mode: Impl,
            cycles: 6,
        },
        0x41 => Instr {
            run: eor,
            mode: XInd,
            cycles: 6,
        },
        0x45 => Instr {
            run: eor,
            mode: Zpg,
            cycles: 3,
        },
        0x46 => Instr {
            run: lsr,
            mode: Zpg,
            cycles: 5,
        },
        0x48 => Instr {
            run: pha,
            mode: Impl,
            cycles: 3,
        },
        0x49 => Instr {
            run: eor,
            mode: Imm,
            cycles: 2,
        },
        0x4A => Instr {
            run: lsr,
            mode: A,
            cycles: 2,
        },
        0x4C => Instr {
            run: jmp,
            mode: Abs,
            cycles: 3,
        },
        0x4D => Instr {
            run: eor,
            mode: Abs,
            cycles: 4,
        },
        0x4E => Instr {
            run: lsr,
            mode: Abs,
            cycles: 6,
        },
        0x50 => Instr {
            run: bvc,
            mode: Rel,
            cycles: 2,
        },
        0x51 => Instr {
            run: eor,
            mode: IndY,
            cycles: 5,
        },
        0x55 => Instr {
            run: eor,
            mode: ZpgX,
            cycles: 4,
        },
        0x56 => Instr {
            run: lsr,
            mode: ZpgX,
            cycles: 6,
        },
        0x58 => Instr {
            run: cli,
            mode: Impl,
            cycles: 2,
        },
        0x59 => Instr {
            run: eor,
            mode: AbsY,
            cycles: 4,
        },
        0x5D => Instr {
            run: eor,
            mode: AbsX,
            cycles: 4,
        },
        0x5E => Instr {
            run: lsr,
            mode: AbsX,
            cycles: 7,
        },
        0x60 => Instr {
            run: rts,
            mode: Impl,
            cycles: 6,
        },
        0x61 => Instr {
            run: adc,
            mode: XInd,
            cycles: 6,
        },
        0x65 => Instr {
            run: adc,
            mode: Zpg,
            cycles: 3,
        },
        0x66 => Instr {
            run: ror,
            mode: Zpg,
            cycles: 5,
        },
        0x68 => Instr {
            run: pla,
            mode: Impl,
            cycles: 4,
        },
        0x69 => Instr {
            run: adc,
            mode: Imm,
            cycles: 2,
        },
        0x6A => Instr {
            run: ror,
            mode: A,
            cycles: 2,
        },
        0x6C => Instr {
            run: jmp,
            mode: Ind,
            cycles: 5,
        },
        0x6D => Instr {
            run: adc,
            mode: Abs,
            cycles: 4,
        },
        0x6E => Instr {
            run: ror,
            mode: Abs,
            cycles: 6,
        },
        0x70 => Instr {
            run: bvs,
            mode: Rel,
            cycles: 2,
        },
        0x71 => Instr {
            run: adc,
            mode: IndY,
            cycles: 5,
        },
        0x75 => Instr {
            run: adc,
            mode: ZpgX,
            cycles: 4,
        },
        0x76 => Instr {
            run: ror,
            mode: ZpgX,
            cycles: 6,
        },
        0x78 => Instr {
            run: sei,
            mode: Impl,
            cycles: 2,
        },
        0x79 => Instr {
            run: adc,
            mode: AbsY,
            cycles: 4,
        },
        0x7D => Instr {
            run: adc,
            mode: AbsX,
            cycles: 4,
        },
        0x7E => Instr {
            run: ror,
            mode: AbsX,
            cycles: 7,
        },
        0x81 => Instr {
            run: sta,
            mode: XInd,
            cycles: 6,
        },
        0x84 => Instr {
            run: sty,
            mode: Zpg,
            cycles: 3,
        },
        0x85 => Instr {
            run: sta,
            mode: Zpg,
            cycles: 3,
        },
        0x86 => Instr {
            run: stx,
            mode: Zpg,
            cycles: 3,
        },
        0x88 => Instr {
            run: dey,
            mode: Impl,
            cycles: 2,
        },
        0x8A => Instr {
            run: txa,
            mode: Impl,
            cycles: 2,
        },
        0x8C => Instr {
            run: sty,
            mode: Abs,
            cycles: 4,
        },
        0x8D => Instr {
            run: sta,
            mode: Abs,
            cycles: 4,
        },
        0x8E => Instr {
            run: stx,
            mode: Abs,
            cycles: 4,
        },
        0x90 => Instr {
            run: bcc,
            mode: Rel,
            cycles: 2,
        },
        0x91 => Instr {
            run: sta,
            mode: IndY,
            cycles: 6,
        },
        0x94 => Instr {
            run: sty,
            mode: ZpgX,
            cycles: 4,
        },
        0x95 => Instr {
            run: sta,
            mode: ZpgX,
            cycles: 4,
        },
        0x96 => Instr {
            run: stx,
            mode: ZpgY,
            cycles: 4,
        },
        0x98 => Instr {
            run: tya,
            mode: Impl,
            cycles: 2,
        },
        0x99 => Instr {
            run: sta,
            mode: AbsY,
            cycles: 5,
        },
        0x9A => Instr {
            run: txs,
            mode: Impl,
            cycles: 2,
        },
        0x9D => Instr {
            run: sta,
            mode: AbsX,
            cycles: 5,
        },
        0xA0 => Instr {
            run: ldy,
            mode: Imm,
            cycles: 2,
        },
        0xA1 => Instr {
            run: lda,
            mode: XInd,
            cycles: 6,
        },
        0xA2 => Instr {
            run: ldx,
            mode: Imm,
            cycles: 2,
        },
        0xA4 => Instr {
            run: ldy,
            mode: Zpg,
            cycles: 3,
        },
        0xA5 => Instr {
            run: lda,
            mode: Zpg,
            cycles: 3,
        },
        0xA6 => Instr {
            run: ldx,
            mode: Zpg,
            cycles: 3,
        },
        0xA8 => Instr {
            run: tay,
            mode: Impl,
            cycles: 2,
        },
        0xA9 => Instr {
            run: lda,
            mode: Imm,
            cycles: 2,
        },
        0xAA => Instr {
            run: tax,
            mode: Impl,
            cycles: 2,
        },
        0xAC => Instr {
            run: ldy,
            mode: Abs,
            cycles: 4,
        },
        0xAD => Instr {
            run: lda,
            mode: Abs,
            cycles: 4,
        },
        0xAE => Instr {
            run: ldx,
            mode: Abs,
            cycles: 4,
        },
        0xB0 => Instr {
            run: bcs,
            mode: Rel,
            cycles: 2,
        },
        0xB1 => Instr {
            run: lda,
            mode: IndY,
            cycles: 5,
        },
        0xB4 => Instr {
            run: ldy,
            mode: ZpgX,
            cycles: 4,
        },
        0xB5 => Instr {
            run: lda,
            mode: ZpgX,
            cycles: 4,
        },
        0xB6 => Instr {
            run: ldx,
            mode: ZpgY,
            cycles: 4,
        },
        0xB8 => Instr {
            run: clv,
            mode: Impl,
            cycles: 2,
        },
        0xB9 => Instr {
            run: lda,
            mode: AbsY,
            cycles: 4,
        },
        0xBA => Instr {
            run: tsx,
            mode: Impl,
            cycles: 2,
        },
        0xBC => Instr {
            run: ldy,
            mode: AbsX,
            cycles: 4,
        },
        0xBD => Instr {
            run: lda,
            mode: AbsX,
            cycles: 4,
        },
        0xBE => Instr {
            run: ldx,
            mode: AbsY,
            cycles: 4,
        },
        0xC0 => Instr {
            run: cpy,
            mode: Imm,
            cycles: 2,
        },
        0xC1 => Instr {
            run: cmp,
            mode: XInd,
            cycles: 6,
        },
        0xC4 => Instr {
            run: cpy,
            mode: Zpg,
            cycles: 3,
        },
        0xC5 => Instr {
            run: cmp,
            mode: Zpg,
            cycles: 3,
        },
        0xC6 => Instr {
            run: dec,
            mode: Zpg,
            cycles: 5,
        },
        0xC8 => Instr {
            run: iny,
            mode: Impl,
            cycles: 2,
        },
        0xC9 => Instr {
            run: cmp,
            mode: Imm,
            cycles: 2,
        },
        0xCA => Instr {
            run: dex,
            mode: Impl,
            cycles: 2,
        },
        0xCC => Instr {
            run: cpy,
            mode: Abs,
            cycles: 4,
        },
        0xCD => Instr {
            run: cmp,
            mode: Abs,
            cycles: 4,
        },
        0xCE => Instr {
            run: dec,
            mode: Abs,
            cycles: 6,
        },
        0xD0 => Instr {
            run: bne,
            mode: Rel,
            cycles: 2,
        },
        0xD1 => Instr {
            run: cmp,
            mode: IndY,
            cycles: 5,
        },
        0xD5 => Instr {
            run: cmp,
            mode: ZpgX,
            cycles: 4,
        },
        0xD6 => Instr {
            run: dec,
            mode: ZpgX,
            cycles: 6,
        },
        0xD8 => Instr {
            run: cld,
            mode: Impl,
            cycles: 2,
        },
        0xD9 => Instr {
            run: cmp,
            mode: AbsY,
            cycles: 4,
        },
        0xDD => Instr {
            run: cmp,
            mode: AbsX,
            cycles: 4,
        },
        0xDE => Instr {
            run: dec,
            mode: AbsX,
            cycles: 7,
        },
        0xE0 => Instr {
            run: cpx,
            mode: Imm,
            cycles: 2,
        },
        0xE1 => Instr {
            run: sbc,
            mode: XInd,
            cycles: 6,
        },
        0xE4 => Instr {
            run: cpx,
            mode: Zpg,
            cycles: 3,
        },
        0xE5 => Instr {
            run: sbc,
            mode: Zpg,
            cycles: 3,
        },
        0xE6 => Instr {
            run: inc,
            mode: Zpg,
            cycles: 5,
        },
        0xE8 => Instr {
            run: inx,
            mode: Impl,
            cycles: 2,
        },
        0xE9 => Instr {
            run: sbc,
            mode: Imm,
            cycles: 2,
        },
        0xEA => Instr {
            run: nop,
            mode: Impl,
            cycles: 2,
        },
        0xEC => Instr {
            run: cpx,
            mode: Abs,
            cycles: 4,
        },
        0xED => Instr {
            run: sbc,
            mode: Abs,
            cycles: 4,
        },
        0xEE => Instr {
            run: inc,
            mode: Abs,
            cycles: 6,
        },
        0xF0 => Instr {
            run: beq,
            mode: Rel,
            cycles: 2,
        },
        0xF1 => Instr {
            run: sbc,
            mode: IndY,
            cycles: 5,
        },
        0xF5 => Instr {
            run: sbc,
            mode: ZpgX,
            cycles: 4,
        },
        0xF6 => Instr {
            run: inc,
            mode: ZpgX,
            cycles: 6,
        },
        0xF8 => Instr {
            run: sed,
            mode: Impl,
            cycles: 2,
        },
        0xF9 => Instr {
            run: sbc,
            mode: AbsY,
            cycles: 4,
        },
        0xFD => Instr {
            run: sbc,
            mode: AbsX,
            cycles: 4,
        },
        0xFE => Instr {
            run: inc,
            mode: AbsX,
            cycles: 7,
        },
        _ => {
            println!("Opcode {:x}", opcode);
            panic!("Err: Unknown instruction")
        }
    }
}
